options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/angular-game-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/angular-game-app']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'angular-game-app',
      '--image', 'gcr.io/$PROJECT_ID/angular-game-app',
      '--platform', 'managed',
      '--region', 'us-central1'
    ]
images:
  - 'gcr.io/$PROJECT_ID/angular-game-app'
